platform :ios, '8.0'
target "ZATools" do
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'YYModel'
pod 'YTKNetwork'
pod 'UMengAnalytics-NO-IDFA'
pod 'MJRefresh', '~> 3.1.12'
pod 'Masonry', '~> 1.0.1'

pod 'React', :path => './RNComponent/node_modules/react-native', :subspecs => [
'Core',
'RCTText',
'RCTNetwork',
'RCTWebSocket',
'RCTImage'
]
 
pod "Yoga", :path => "./RNComponent/node_modules/react-native/ReactCommon/yoga"

end
